---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/kymppi/k8s-cluster
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
