---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: git-credentials
  url: https://github.com/kymppi/k8s-cluster.git
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
