apiVersion: v1
data:
  sops: ENC[AES256_GCM,data:NMO1mJsKhwE=,iv:PBsyYyO4gVoRSrjPWH8wJFEP2QOr8nLS+fjreOn/OT4=,tag:J1LzlaJ2TWfW7kmKbNBpOw==,type:str]
kind: Secret
metadata:
  namespace: flux-system
  name: sopstest
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1df5fjnn0j202w390f66dka3ezcylgeywahgkzjk3gz7vl3jlua4se5v6pu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSkZnTXNxRWY0TWc2OTlJ
        MWNmVkp4bU5scWZqM2x6bUVDcW9rbWlPazNZCmxoWVoxRG1jN1NlUDFnbkhsR2NQ
        MmVBUWc4eFRFbFNtbTR6UWtmYmRiTUUKLS0tIEwrTDNXUFUxSi9pWDJaZmhaZnAy
        VGxnR0FMN01EWUU4SElOMUVTZGFFWk0KPJ7PRB1i1wX5lVwhGHm06Ig9ldjPe3eR
        CQFn46W6F8Xv63Rc2dkav1Nyxx68B10uZJWqNj95T8WDz7kTn6AuhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-06-27T19:11:07Z'
  mac: ENC[AES256_GCM,data:Jf73PqY97BK9HMIviYCZWYi0JA7lfp0YmdnIOXMwuhMo8XlpTSAbAMst9dV4Z5zqSmqJnAXVZo+EJAajMGHoXfocgB3bT9t8rMlOvPBfOyE9+bnHL2sXS3gLB51ZbXK5xBo8J258jfaWFzEkssiPJX571V7gOT+k1vTSphXVgNQ=,iv:wmVsGW6vW0XsdNPWrvFa84oEjr6likP2U3XGw15Iqdk=,tag:rhwKT2xpkavxSUvRYCdu4g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
