---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cilium
  namespace: flux-system
spec:
  interval: 10m
  path: './kubernetes/apps/kube-system/cilium/app'
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  wait: true
