# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: bitwarden
#   namespace: kube-system
# spec:
#   dependsOn:
#     - name: external-secrets
#       namespace: kube-system
#   interval: 5m
#   chart:
#     spec:
#       chart: app-template
#       version: 1.5.1
#       sourceRef:
#         kind: HelmRepository
#         name: bjw-s
#         namespace: flux-system
#       interval: 5m
#   values:
#     image:
#       repository: ghcr.io/larivierec/bitwarden-cli
#       tag: latest
#     envFrom:
#       - secretRef:
#           name: bitwarden-cli
#     service:
#       main:
#         ports:
#           http:
#             port: 8087
#     probes:
#       liveness:
#         enabled: true
#         custom: true
#         spec:
#           exec:
#             command:
#               - wget
#               - -q
#               - http://127.0.0.1:8087/sync?force=true
#               - --post-data=''
#       readiness:
#         enabled: false
#     resources:
#       requests:
#         memory: 256Mi
#         cpu: 100m
#       limits:
#         memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden-cli
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: bitwarden-cli
    app.kubernetes.io/name: bitwarden-cli
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: bitwarden-cli
      app.kubernetes.io/instance: bitwarden-cli
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitwarden-cli
        app.kubernetes.io/instance: bitwarden-cli
    spec:
      containers:
        - name: bitwarden-cli
          image: ghcr.io/d2checkpoint-com/bw-docker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BW_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: bitwarden-cli
                  key: BW_CLIENTID
            - name: BW_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: bitwarden-cli
                  key: BW_CLIENTSECRET
            - name: BW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bitwarden-cli
                  key: BW_PASSWORD
          ports:
            - name: http
              containerPort: 8087
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - wget
                - -q
                - http://127.0.0.1:8087/sync?force=true
                - --post-data=''
            initialDelaySeconds: 20
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 120 # sync vault every 2 minutes
          readinessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 20
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 10
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 128Mi
          #   limits:
          #     cpu: 100m
          #     memory: 128Mi
          # temporarily remove limits since it got OOMKilled
---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden-cli
  namespace: bitwarden
  labels:
    app.kubernetes.io/instance: bitwarden-cli
    app.kubernetes.io/name: bitwarden-cli
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: bitwarden-cli
    app.kubernetes.io/instance: bitwarden-cli
---
# allow only external-secrets to access the bitwarden-cli
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: external-secret-2-bw-cli
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: bitwarden-cli
      app.kubernetes.io/name: bitwarden-cli
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: external-secrets
            app.kubernetes.io/name: external-secrets
      toPorts:
        - ports:
            - port: '8087'
