---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age