apiVersion: apps/v1
kind: Deployment
metadata:
  name: writefreely
  namespace: default
  labels:
    app: writefreely
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writefreely
  template:
    metadata:
      labels:
        app: writefreely
    spec:
      imagePullSecrets:
        - name: ghcr-io-registry
      containers:
        - name: writefreely
          image: ghcr.io/kymppi/writefreely-docker:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /go/config.ini
              subPath: config.ini
            - name: data
              mountPath: /data/
          ports:
            - containerPort: 8080
      initContainers:
        - name: install
          image: ghcr.io/kymppi/writefreely-docker:latest
          imagePullPolicy: Always
          command:
            - './cmd/writefreely/writefreely'
            - '-gen-keys'
          volumeMounts:
            - name: config
              mountPath: /config/config.ini
              subPath: config.ini
            - name: data
              mountPath: /data/
      volumes:
        - name: config
          configMap:
            name: wfconfig
        - name: data
          persistentVolumeClaim:
            claimName: writefreely-data
---
apiVersion: v1
kind: Service
metadata:
  name: writefreely
spec:
  type: ClusterIP
  selector:
    app: writefreely
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: writefreely
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`i11l.blog`)
      kind: Rule
      services:
        - name: writefreely
          port: 80
          kind: Service
  tls:
    certResolver: le
