---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: writefreely-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
