---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xbackbone-php
  namespace: default
data:
  php-local.ini: |
    upload_max_filesize = 25M
    post_max_size = 25M
  www2.conf: |
    ; Edit this file to override www.conf and php-fpm.conf directives and restart the container

    ; Pool name
    [www]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xbackbone-config
  namespace: default
data:
  config.php: |
    <?php
    return array (
      'base_url' => 'https://i.i11l.blog',
      'db' =>
      array (
        'connection' => 'sqlite',
        'dsn' => '/app/www/public/resources/database/xbackbone.sqlite',
        'username' => NULL,
        'password' => NULL,
      ),
      'storage' => array (
        'driver' => 's3',
        'key' => file_get_contents('/etc/secrets/s3-credentials/key'),
        'secret' => file_get_contents('/etc/secrets/s3-credentials/secret'),
        'region' => file_get_contents('/etc/secrets/s3-credentials/region'),
        'bucket' => file_get_contents('/etc/secrets/s3-credentials/bucket'),
        'endpoint' => file_get_contents('/etc/secrets/s3-credentials/endpoint'),
        'use_path_style_endpoint' => true,
        'path' => '/',
      ),
    );
