apiVersion: apps/v1
kind: Deployment
metadata:
  name: xbackbone
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xbackbone
  template:
    metadata:
      labels:
        app: xbackbone
    spec:
      containers:
        - name: xbackbone
          image: lscr.io/linuxserver/xbackbone:latest
          env:
            - name: PUID
              value: '911' # LSIO default
            - name: PGID
              value: '911'
            - name: TZ
              value: 'Etc/UTC'
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            # - name: php-config
            #   mountPath: /config/php
            # - name: config
            #   mountPath: /config/www/xbackbone
            - name: secrets
              mountPath: /etc/secrets/s3-credentials
            - name: data
              mountPath: '/config'

      initContainers: # need to do this because if I use the configMap directly, it will be mounted as read-only
        - name: copy-configs
          image: busybox
          command:
            [
              'sh',
              '-c',
              'rm -rf /config/php/* /config/www/xbackbone/config.php && mkdir -p /config/php /config/www/xbackbone && cp /pre-php/* /config/php/ && cp /pre-config/* /config/www/xbackbone/',
            ]
          volumeMounts:
            - name: pre-php-config
              mountPath: /pre-php
            - name: pre-config
              mountPath: /pre-config
            - name: data
              mountPath: /config
        - name: chown-database-folder
          image: busybox
          command: ['sh', '-c', 'chown -R 911:911 /config']
          volumeMounts:
            - name: data
              mountPath: /config/www/xbackbone/resources
      volumes:
        - name: php-config
          emptyDir: {}
        - name: config
          emtpryDir: {}
        - name: pre-php-config
          configMap:
            name: xbackbone-php
            items:
              - key: php-local.ini
                path: php-local.ini
              - key: www2.conf
                path: www2.conf
        - name: pre-config
          configMap:
            name: xbackbone-config
            items:
              - key: config.php
                path: config.php
        - name: secrets
          secret:
            secretName: xbackbone-external-secret
            items:
              - key: key
                path: key
              - key: secret
                path: secret
              - key: region
                path: region
              - key: bucket
                path: bucket
              - key: endpoint
                path: endpoint
        - name: data
          persistentVolumeClaim:
            claimName: xbackbone-data
---
apiVersion: v1
kind: Service
metadata:
  name: xbackbone
  namespace: default
spec:
  selector:
    app: xbackbone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: xbackbone
  namespace: default
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`i.i11l.blog`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: xbackbone
          port: 80
          kind: Service
  tls:
    certResolver: le
