---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xbackbone-external-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        key: |-
          {{ .S3_ACCESS_KEY }}
        secret: |-
          {{ .S3_SECRET_KEY }}
        region: |-
          {{ .S3_REGION }}
        bucket: |-
          {{ .S3_BUCKET }}
        endpoint: |-
          {{ .S3_ENDPOINT }}
  data:
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: b19264d1-6e2e-4544-a88e-b07e014e724e
        property: key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: b19264d1-6e2e-4544-a88e-b07e014e724e
        property: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: S3_REGION
      remoteRef:
        key: b19264d1-6e2e-4544-a88e-b07e014e724e
        property: region
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: S3_BUCKET
      remoteRef:
        key: b19264d1-6e2e-4544-a88e-b07e014e724e
        property: bucket
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: b19264d1-6e2e-4544-a88e-b07e014e724e
        property: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
