---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # autoDirectNodeRoutes: true
    # bpf:
    #   masquerade: true
    # bgp:
    #   enabled: false
    # cluster:
    #   name: midka
    #   id: 1
    # containerRuntime:
    #   integration: containerd
    #   socketPath: /var/run/k3s/containerd/containerd.sock
    # endpointRoutes:
    #   enabled: true
    # # hubble:
    # #   enabled: false
    # #   metrics:
    # #     enabled:
    # #       - dns:query
    # #       - drop
    # #       - tcp
    # #       - flow
    # #       - port-distribution
    # #       - icmp
    # #       - http
    # #     serviceMonitor:
    # #       enabled: false
    # #   relay:
    # #     enabled: true
    # #     rollOutPods: true
    # #   ui:
    # #     enabled: true
    # #     rollOutPods: true
    # #     ingress:
    # #       enabled: true
    # #       className: internal
    # #       annotations:
    # #         hajimari.io/icon: simple-icons:cilium

    # ipam:
    #   mode: kubernetes
    # k8sServiceHost: '10.43.0.10'
    # k8sServicePort: 6443
    # ipv4NativeRoutingCIDR: '172.30.0.0/16'
    # kubeProxyReplacement: strict
    # kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    # operator:
    #   rollOutPods: true
    # rollOutCiliumPods: true
    # l2announcements:
    #   enabled: true
    #   leaseDuration: 120s
    #   leaseRenewDeadline: 60s
    #   leaseRetryPeriod: 1s
    # loadBalancer:
    #   algorithm: 'maglev'
    #   mode: 'dsr'
    # localRedirectPolicy: true
    # securityContext:
    #   privileged: true
    # tunnel: 'disabled'
    # ipv6:
    #   enabled: true

    autoDirectNodeRoutes: true
    bgp:
      enabled: false
    bpf:
      masquerade: true
    cluster:
      id: 1
      name: midka
    containerRuntime:
      integration: containerd
      socketPath: /var/run/k3s/containerd/containerd.sock
    endpointRoutes:
      enabled: true
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: 172.30.0.0/16
    ipv6:
      enabled: true
    k8sServiceHost: kubernetes.default.svc.cluster.local
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    l2announcements:
      enabled: true
      leaseDuration: 120s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 1s
    loadBalancer:
      algorithm: maglev
      mode: dsr
    localRedirectPolicy: true
    operator:
      rollOutPods: true
    rollOutCiliumPods: true
    securityContext:
      privileged: true
    tunnel: disabled
    # ipv6:
    #   enabled: true
