---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-loki-secrets
  namespace: monitoring
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        aws_endpoint: |-
          {{ .AWS_ENDPOINT }}
  data:
    - secretKey: AWS_ENDPOINT
      remoteRef:
        key: 6617e692-8546-4534-b47f-b19f0097e429
        property: aws_endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
