---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-loki-secrets
  namespace: monitoring
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        AWS_ENDPOINT: |-
          {{ .AWS_ENDPOINT }}
        AWS_ACCESS_KEY_ID: |-
          {{ .AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ .AWS_SECRET_ACCESS_KEY }}
  data:
    - secretKey: AWS_ENDPOINT
      remoteRef:
        key: 6617e692-8546-4534-b47f-b19f0097e429
        property: aws_endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: 6617e692-8546-4534-b47f-b19f0097e429
        property: aws_access_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: 6617e692-8546-4534-b47f-b19f0097e429
        property: aws_secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
