---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-other
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/flux-system/other
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: kube-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
