---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: kube-system
spec:
  path: ./kubernetes/apps/kube-system/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
