---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero
  namespace: kube-system
spec:
  target:
    name: velero-s3-creds
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id = {{ .access-key-id }}
          aws_secret_access_key = {{ .secret-access-key }}
  data:
    - secretKey: access-key-id
      key: access-key-id
      name: access-key-id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7be5a97a-3160-444f-8af1-b052010bc34f
        property: access-key-id
    - secretKey: secret-access-key
      key: secret-access-key
      name: secret-access-key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7be5a97a-3160-444f-8af1-b052010bc34f
        property: secret-access-key
