---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero
  namespace: kube-system
spec:
  target:
    name: velero-s3-creds
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id = {{ .ACCESS_KEY_ID }}
          aws_secret_access_key = {{ .SECRET_ACCESS_KEY }}
  data:
    - secretKey: ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7be5a97a-3160-444f-8af1-b052010bc34f
        property: access-key-id
    - secretKey: SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7be5a97a-3160-444f-8af1-b052010bc34f
        property: secret-access-key
