---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 3.1.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/velero
    configuration:
      extraEnvVars:
        TZ: 'Etc/UTC'
      provider: aws
      backupStorageLocation:
        name: default
        bucket: kube
        config:
          s3ForcePathStyle: true
          s3Url: https://s3.midka.dev
          publicUrl: https://jupiter.midka.dev
      resticTimeout: 6h
    initContainers:
      - name: velero-plugin-for-aws
        image: ghcr.io/k8s-at-home/velero-plugin-for-aws:v1.5.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    credentials:
      existingSecret: velero-s3-creds
    schedules:
      daily-backup:
        schedule: '0 6 * * *'
        template:
          ttl: '120h'
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    snapshotsEnabled: true
    upgradeCRDs: false
    cleanUpCRDs: false
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
        - key: 'node-role.kubernetes.io/master'
          operator: 'Exists'
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi
          cpu: 1000m
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
        cpu: 200m
