---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-velero
  namespace: kube-system
spec:
  interval: 10m
  path: './kubernetes/apps/kube-system/velero/app'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets
