---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-other
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/flux/other
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  dependsOn:
    - name: cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
