apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventofcode
  namespace: default
  labels:
    app: adventofcode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adventofcode
  template:
    metadata:
      labels:
        app: adventofcode
    spec:
      securityContext:
        runAsUser: 2
        runAsGroup: 2
        fsGroup: 2
      imagePullSecrets:
        - name: ghcr-io-registry
      initContainers:
        - name: envsubst
          image: 'dibi/envsubst'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /workdir/settings.toml
              subPath: settings.toml
              readOnly: true
            - name: processed
              mountPath: /processed
          env:
            - name: SESSION_COOKIE
              valueFrom:
                secretKeyRef:
                  name: adventofcode
                  key: session_cookie
        - name: copy
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            ['sh', '-c', 'cp /processed/settings.toml /app/settings.toml']
          volumeMounts:
            - name: processed
              mountPath: /processed
              readOnly: true
            - name: appconfig
              mountPath: /app/
      containers:
        - name: adventofcode
          image: ghcr.io/kymppi/aocleaderboard:d40c81ee12ff560573f8c9380b90932a3dfe0518 # v1.0.4
          imagePullPolicy: Always
          volumeMounts:
            - name: appconfig
              mountPath: /config/
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 20Mi
            limits:
              cpu: 200m
              memory: 200Mi
      volumes:
        - name: config
          configMap:
            name: adventofcodeconfig
        - name: processed
          emptyDir: {}
        - name: appconfig
          emtpyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: adventofcode
spec:
  type: ClusterIP
  selector:
    app: adventofcode
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: adventofcode
  namespace: default
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`advent.procoderhangout.org`)
      kind: Rule
      services:
        - name: adventofcode
          port: 80
          kind: Service
  tls:
    certResolver: le
