---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: adventofcode-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        session_cookie: |-
          {{ .SESSION_COOKIE }}
  data:
    - secretKey: SESSION_COOKIE
      remoteRef:
        key: 35790515-06a1-429c-bfa2-b0cd00d94514
        property: session_cookie
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
