kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-per-volume
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: '2'
  staleReplicaTimeout: '2880' # 48 hours in minutes
  fromBackup: ''
  fsType: 'ext4'
  encrypted: 'true'
  # per volume secret which utilizes the `pvc.name` and `pvc.namespace` template parameters
  csi.storage.k8s.io/provisioner-secret-name: ${pvc.name}
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/node-publish-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-publish-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/node-stage-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-stage-secret-namespace: ${pvc.namespace}
