---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-cluster
spec:
  instances: 2
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
