---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: miniflux-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin_username: |-
          {{ .ADMIN_USERNAME }}
        admin_password: |-
          {{ .ADMIN_PASSWORD }}
  data:
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: fabc88b6-d72d-47c0-af08-b11600f655db
        property: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: fabc88b6-d72d-47c0-af08-b11600f655db
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
