apiVersion: v1
kind: ConfigMap
data:
  config.ini: |
    [database]
    type = postgres
    host = $__file{/etc/secrets/host}
    name = $__file{/etc/secrets/dbname}
    user = $__file{/etc/secrets/user}
    password = $__file{/etc/secrets/password}
metadata:
  name: grafana-config
  namespace: monitoring
