---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: monitoring
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        secret_key: |-
          {{ .SECURITY_SECRET_KEY }}
  data:
    - secretKey: SECURITY_SECRET_KEY
      remoteRef:
        key: b16d1406-4e33-4eb8-91b7-b0d30142df02
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
