---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.59.4
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    replicas: 1
    deploymentStrategy:
      type: Recreate

    grafana.ini:
      security:
        admin_user: admin
        admin_password: admin

      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
        reporting_enabled: false
      date_formats:
        use_browser_locale: true
      explore:
        enabled: true
      log:
        mode: console
      news:
        news_feed_enabled: false
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
        security:
          allow_embedding: true
          cookie_samesite: grafana
      server:
        root_url: https://grafana.midka.dev

    persistence:
      enabled: true
      existingClaim: grafana-data

    resources:
      limits:
        memory: 219M
      requests:
        cpu: 23m
        memory: 127M

    serviceMonitor:
      enabled: false

    datasources:
      enabled: true
      labelValue: ''
      searchNamespace: ALL
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          - name: Loki
            orgId: 1
          - name: Alertmanager
            orgId: 1
