---
apiVersion: v1
kind: ConfigMap
data:
  mimir.yaml: |
    common:
      storage:
        backend: s3
        s3:
          endpoint: "${AWS_ENDPOINT}"
          region: eu-north-1
          secret_access_key: "${AWS_SECRET_ACCESS_KEY}" # This is a secret injected via an environment variable
          access_key_id: "${AWS_ACCESS_KEY_ID}" # This is a secret injected via an environment variable

    blocks_storage:
      s3:
        bucket_name: mimir-blocks

    alertmanager_storage:
      s3:
        bucket_name: mimir-alertmanager

    ruler_storage:
      s3:
        bucket_name: mimir-ruler

    memberlist:
      cluster_label: mimir
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
      '$status $body_bytes_sent "$http_referer" '
      '"$http_user_agent" "$http_x_forwarded_for"';

      access_log /var/log/nginx/access.log main;

      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;

      map $http_authorization $auth_header_present {
        default 0;
        "~.*" 1;
      }

      server {
        listen 80;
        server_name _;

        location / {
          if ($auth_header_present = 0) {
            return 401;
          }

          auth_request /auth;
          auth_request_set $auth_status $upstream_status;
          auth_request_set $x_scope_orgid $upstream_http_x_scope_orgid;

          proxy_set_header X-Scope-Orgid $x_scope_orgid;

          proxy_pass http://localhost:8080/;
        }

        location /auth {
          internal;
          # auth server url here
          proxy_pass http://grafana-multitenancy.monitoring.svc.cluster.local:3000/auth/;
          proxy_pass_request_body off;
          proxy_set_header Content-Length "";
          proxy_set_header X-Original-URI $request_uri;
          proxy_set_header X-Original-Remote-Addr $remote_addr;
        }
      }
    }
metadata:
  name: grafana-mimir-config
  namespace: monitoring
