---
apiVersion: v1
kind: ConfigMap
data:
  mimir.yaml: |
    common:
      storage:
        backend: s3
        s3:
          endpoint: "${AWS_ENDPOINT}"
          region: eu-north-1
          secret_access_key: "${AWS_SECRET_ACCESS_KEY}" # This is a secret injected via an environment variable
          access_key_id: "${AWS_ACCESS_KEY_ID}" # This is a secret injected via an environment variable

    blocks_storage:
      s3:
        bucket_name: mimir-blocks

    alertmanager_storage:
      s3:
        bucket_name: mimir-alertmanager

    ruler_storage:
      s3:
        bucket_name: mimir-ruler
metadata:
  name: grafana-mimir-config
  namespace: monitoring
