---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-mimir-secrets
  namespace: monitoring
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        aws_endpoint: |-
          {{ .AWS_ENDPOINT }}
        aws_access_key_id: |-
          {{ .AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: |-
          {{ .AWS_SECRET_ACCESS_KEY }}
  data:
    - secretKey: AWS_ENDPOINT
      remoteRef:
        key: 9b5a1cf3-1614-4dc3-9064-b0d80129fd36
        property: aws_endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: 9b5a1cf3-1614-4dc3-9064-b0d80129fd36
        property: aws_access_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: 9b5a1cf3-1614-4dc3-9064-b0d80129fd36
        property: aws_secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
