---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - name: traefik
          image: traefik:2.5.4
          args:
            - '--entryPoints.web.address=:8000/tcp'
            - '--entryPoints.websecure.address=:8443/tcp'
            - '--entryPoints.traefik.address=:9000/tcp'
            - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
            - '--api=true'
            - '--api.dashboard=true'
            - '--ping=true'
            - '--providers.kubernetescrd'
            - '--providers.kubernetescrd.allowCrossNamespace=true'
            - '--api.insecure=true'
            - '--certificatesresolvers.le.acme.email=ssl@midka.dev'
            - '--certificatesresolvers.le.acme.storage=/data/acme.json'
            - '--certificatesresolvers.le.acme.httpchallenge=true'
            - '--certificatesresolvers.le.acme.httpchallenge.entrypoint=web'
            - '--certificatesresolvers.le-staging.acme.email=ssl@midka.dev'
            - '--certificatesresolvers.le-staging.acme.storage=/data/acme-staging.json'
            - '--certificatesresolvers.le-staging.acme.tlschallenge=true'
            - '--certificatesresolvers.le-staging.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory'
          readinessProbe:
            httpGet:
              path: /ping
              port: 9000
            failureThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: /ping
              port: 9000
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2

          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 50Mi

          ports:
            - name: web
              containerPort: 8000
              protocol: TCP
              hostPort: 80

            - name: websecure
              containerPort: 8443
              protocol: TCP
              hostPort: 443

            - name: traefik
              containerPort: 9000
              protocol: TCP

          volumeMounts:
            - mountPath: /data
              name: storage-volume
      volumes:
        - name: storage-volume
          emptyDir: {}
