---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-tempo-secrets
  namespace: monitoring
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        aws_endpoint: |-
          {{ .AWS_ENDPOINT }}
        aws_access_key_id: |-
          {{ .AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: |-
          {{ .AWS_SECRET_ACCESS_KEY }}
  data:
    - secretKey: AWS_ENDPOINT
      remoteRef:
        key: 84545b1d-7940-4357-9637-b1ab00bcbfd9
        property: aws_endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: 84545b1d-7940-4357-9637-b1ab00bcbfd9
        property: aws_access_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: 84545b1d-7940-4357-9637-b1ab00bcbfd9
        property: aws_secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
