---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-conf
  namespace: analytics
data:
  # Add your configuration key-value pairs here
  DISABLE_REGISTRATION: invite_only
  BASE_URL: https://plausible.65.21.101.130.nip.io:443
  MAILER_EMAIL: plausible@midka.dev
  SMTP_HOST_ADDR: mail.qdi.fi
  SMTP_HOST_PORT: '587'
  CLICKHOUSE_DATABASE_URL: http://plausible-events-db:8123/plausible_events_db
  DATABASE_URL: http://postgres:postgres@plausible-db:5432/plausible
