---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-conf
  namespace: analytics
data:
  # Add your configuration key-value pairs here
  DISABLE_REGISTRATION: invite_only
  BASE_URL: http://65.21.101.130/plausible
  MAILER_EMAIL: plausible@midka.dev
  SMTP_HOST_ADDR: mail.qdi.fi
  SMTP_HOST_PORT: '587'
