---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible-db
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plausible-db
  template:
    metadata:
      labels:
        app: plausible-db
    spec:
      containers:
        - name: plausible-db
          image: postgres:15-alpine
          restartPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              # if using "/var/lib/postgresql/data" it gives an initialization error because its a mount point
              mountPath: /var/lib/postgresql
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plausible-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible-events-db
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plausible-events-db
  template:
    metadata:
      labels:
        app: plausible-events-db
    spec:
      containers:
        - name: plausible-events-db
          image: clickhouse/clickhouse-server:22.8.13.20-alpine
          restartPolicy: Always
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: event-data
              mountPath: /var/lib/clickhouse
            - name: clickhouse-config
              mountPath: /etc/clickhouse-server/config.d/config.xml
              subPath: clickhouse-config.xml
              readOnly: true
            - name: clickhouse-user-config
              mountPath: /etc/clickhouse-server/users.d/config.xml
              subPath: clickhouse-user-config.xml
              readOnly: true
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi

      volumes:
        - name: clickhouse-config
          configMap:
            name: clickhouse-config
        - name: clickhouse-user-config
          configMap:
            name: clickhouse-user-config
        - name: event-data
          persistentVolumeClaim:
            claimName: plausible-events-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  namespace: analytics
  labels:
    app: busybox1
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - '3600'
      imagePullPolicy: IfNotPresent
      name: busybox
      volumeMounts:
        - name: data
          mountPath: /mnt
  restartPolicy: Always
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: plausible-events-pvc
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: plausible
#   namespace: analytics
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: plausible
#   template:
#     metadata:
#       labels:
#         app: plausible
#     spec:
#       containers:
#         - name: plausible
#           image: plausible/analytics:v1.5
#           restartPolicy: Always
#           command: [/bin/sh, -c]
#           args:
#             - sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run
#           ports:
#             - containerPort: 8000
#           env:
#             - name: POSTGRES_PASSWORD
#               value: postgres
#           envFrom:
#             - secretRef:
#                 name: plausible-external-secret-secret
#             - configMapRef:
#                 name: plausible-conf
#           resources:
#             limits:
#               cpu: 150m
#               memory: 600Mi
#             requests:
#               cpu: 150m
#               memory: 600Mi
