---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plausible-external-secret
  namespace: analytics
spec:
  target:
    name: plausible-external-secret-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        secret-key-base: |-
          {{ .SECRET_KEY_BASE }}
        smtp-user-pwd: |-
          {{ .SMTP_USER_PWD }}
        smtp-user-name: |-
          {{ .SMTP_USER_NAME }}
  data:
    - secretKey: SECRET_KEY_BASE
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f7d73c1b-1453-4a3d-820c-b03900ea0ab4
        property: SECRET_KEY_BASE
    - secretKey: SMTP_USER_PWD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f7d73c1b-1453-4a3d-820c-b03900ea0ab4
        property: SMTP_USER_PWD
    - secretKey: SMTP_USER_NAME
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f7d73c1b-1453-4a3d-820c-b03900ea0ab4
        property: SMTP_USER_NAME
