---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: plausible
spec:
  rules:
    - http:
        paths:
          - path: /plausible
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 5678
