---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plausible
  namespace: analytics
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`testing.midka.dev`)
      kind: Rule
      services:
        - name: plausible
          port: 8000
