apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./volume.yaml
  - ./service.yaml
  - ./ingress.yaml
metadata:
  namespace: analytics
  name: plausible
configMapGenerator:
  - name: clickhouse-config
    files:
      - clickhouse-config.xml
  - name: clickhouse-user-config
    files:
      - clickhouse-user-config.xml
