apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-events-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-per-volume
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-per-volume
  resources:
    requests:
      storage: 512Mi
