apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-events-pvc
  namespace: analytics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-db-pvc
  namespace: analytics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
