---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 55.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  values:
    fullnameOverride: kps
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        retention: 6h
        replicas: 1
        replicaExternalLabelName: __replica__
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        enableAdminAPI: true
        walCompression: true
        enableFeatures:
          - auto-gomaxprocs
          - memory-snapshot-on-shutdown
          - new-service-discovery-manager
        remoteWrite:
          - url: http://mimir.monitoring.svc.cluster.local:8080/api/v1/push
            headers:
              X-Scope-Orgid: '1'
        externalLabels:
          cluster: cluster
    prometheus-node-exporter:
      fullnameOverride: node-exporter
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: instance
      kubelet:
        serviceMonitor:
          cAdvisorMetricRelabelings:
            # https://github.com/prometheus-community/helm-charts/issues/2133
            # Drop less useful container CPU metrics.
            - sourceLabels: [__name__]
              action: drop
              regex: 'container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)'
            # Drop less useful container / always zero filesystem metrics.
            - sourceLabels: [__name__]
              action: drop
              regex: 'container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)'
            # Drop less useful / always zero  container memory metrics.
            - sourceLabels: [__name__]
              action: drop
              regex: 'container_memory_(mapped_file|swap)'
            # Drop less useful container process metrics.
            - sourceLabels: [__name__]
              action: drop
              regex: 'container_(file_descriptors|tasks_state|threads_max)'
            # Drop container spec metrics that overlap with kube-state-metrics.
            - sourceLabels: [__name__]
              action: drop
              regex: 'container_spec.*'
            # Drop cgroup metrics with no pod.
            - sourceLabels: [id, pod]
              action: drop
              regex: '.+;'
            # Drop cgroup metrics with no container.
            - sourceLabels: [id, container]
              action: drop
              regex: '.+;'
    grafana:
      enabled: false
