---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./longhorn.yaml
  - ./bjw-s.yaml
  - ./external-secrets.yaml
  - ./vmware-tanzu.yaml
  - ./cilium.yaml
  - ./traefik.yaml
  - ./grafana.yaml
  - ./jetstack.yaml
