---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-mimir-secrets
  namespace: monitoring
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        jwt_allowed_issuer: |-
          {{ .JWT_ALLOWED_ISSUER }}
        jwt_secret_key: |-
          {{ .JWT_SECRET_KEY }}
  data:
    - secretKey: JWT_ALLOWED_ISSUER
      remoteRef:
        key: 42b74552-809d-4d55-a47f-b0d8012f1fac
        property: jwt_allowed_issuer
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: 42b74552-809d-4d55-a47f-b0d8012f1fac
        property: jwt_secret_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
